apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-2
  labels:
    app: todo-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app-2
  template:
    metadata:
      labels:
        app: todo-app-2
    spec:
      containers:
      - name: todo
        image: amirsha99/todo-app:8
        ports:
        - containerPort: 8000
