apiVersion: v1
kind: Service
metadata:
  name: todo-service-2
spec:
  type: NodePort
  selector:
    app: todo-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31000
